In [1]:
catalog.list()

['companies', 'reviews', 'shuttles', 'parameters']

In [3]:
df= catalog.load ('companies')

[03/03/23 19:49:55] INFO     Loading data from 'companies' (CSVDataSet)...                      ]8;id=568620;file:///opt/anaconda3/envs/kedro-environment/lib/python3.10/site-packages/kedro/io/data_catalog.py\data_catalog.py]8;;\:]8;id=607935;file:///opt/anaconda3/envs/kedro-environment/lib/python3.10/site-packages/kedro/io/data_catalog.py#343\343]8;;\

In [4]:
df.head(10)

,id,company_rating,company_location,total_fleet_count,iata_approved
0,35029,100%,Niue,4.0,f
1,30292,67%,Anguilla,6.0,f
2,19032,67%,Russian Federation,4.0,f
3,8238,91%,Barbados,15.0,t
4,30342,NaN,Sao Tome and Principe,2.0,t
5,32413,100%,Faroe Islands,1.0,f
6,35620,90%,Micronesia,3.0,f
7,23820,NaN,Rwanda,1.0,t
8,46528,100%,Uzbekistan,3.0,t
9,11875,100%,Micronesia,2.0,t

In [5]:
df1= catalog.load ('shuttles')

[03/03/23 19:52:16] INFO     Loading data from 'shuttles' (ExcelDataSet)...                     ]8;id=687057;file:///opt/anaconda3/envs/kedro-environment/lib/python3.10/site-packages/kedro/io/data_catalog.py\data_catalog.py]8;;\:]8;id=139647;file:///opt/anaconda3/envs/kedro-environment/lib/python3.10/site-packages/kedro/io/data_catalog.py#343\343]8;;\

In [6]:
df1.head(10)

,id,shuttle_location,shuttle_type,engine_type,engine_vendor,engines,passenger_capacity,cancellation_policy,crew,d_check_complete,moon_clearance_complete,price,company_id
0,63561,Niue,Type V5,Quantum,ThetaBase Services,1.0,2,strict,1.0,f,f,"$1,325.0",35029
1,36260,Anguilla,Type V5,Quantum,ThetaBase Services,1.0,2,strict,1.0,t,f,"$1,780.0",30292
2,57015,Russian Federation,Type V5,Quantum,ThetaBase Services,1.0,2,moderate,0.0,f,f,"$1,715.0",19032
3,14035,Barbados,Type V5,Plasma,ThetaBase Services,3.0,6,strict,3.0,f,f,"$4,770.0",8238
4,10036,Sao Tome and Principe,Type V2,Plasma,ThetaBase Services,2.0,4,strict,2.0,f,f,"$2,820.0",30342
5,45163,Sao Tome and Principe,Type V5,Plasma,ThetaBase Services,2.0,4,moderate,2.0,f,f,"$1,715.0",32413
6,64643,Faroe Islands,Type F5,Quantum,ThetaBase Services,1.0,2,strict,1.0,t,f,"$1,247.0",35620
7,23389,Micronesia,Type V5,Quantum,ThetaBase Services,1.0,1,moderate,1.0,f,f,"$1,845.0",23820
8,39934,Rwanda,Type V5,Quantum,ThetaBase Services,1.0,3,strict,2.0,f,f,"$1,520.0",46528
9,57063,Faroe Islands,Type F5,Plasma,ThetaBase Services,4.0,8,strict,5.0,f,f,"$3,275.0",11875